version: 2

jobs:
  flutter-setup:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Run Flutter doctor
          command: flutter doctor
      - run:
          name: Accept Android tool chain licences
          command: (yes || true) | flutter doctor --android-licenses
  flutter-test:
    docker:
      - image: cirrusci/flutter
    steps:
      - run:
          name: Run Flutter doctor
          command: flutter doctor

workflows:
  version: 2
  push-workflow:
    jobs:
      - flutter-setup
      - flutter-test:
          requires:
            - flutter-setup

